{* version=2; *}
<div class="double_tier_left_bloc_black_menu">
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:6px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='fiche-detail' base=$record->base_type id=$record->get_id() title=$record->title_encode}"><img src="/img/home.png" width="32" alt="icone home" title="icone home" style="border:0px;"></a></div>
	{if $menu == "serie"}<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='episodes-series' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">Episodes</a><br/><span style="color:gray;font-size:10px;">et les saisons...</span></div>{/if}
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if count($record->trailer) == 0}color:gray{/if}">{if count($record->trailer) > 0}<a href="{url alias='bande-annonce-film' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">{/if}Bande-annonce{if count($record->trailer) > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">et toutes les vidéos...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='casting' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">Casting</a><br/><span style="color:gray;font-size:10px;">complet...</span></div>
	{if $menu == "serie"}<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='diffusion-tv' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">Diffusion Tv</a><br/><span style="color:gray;font-size:10px;">et les horaires...</span></div>{/if}
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='critique-film' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">Critiques</a><br/><span style="color:gray;font-size:10px;">presse et vous...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if $record->photo['count'] == 0}color:gray{/if}">{if $record->photo['count'] > 0}<a href="{url alias='photo-film' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">{/if}Photos{if $record->photo['count'] > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">du film...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if $record->news['count'] == 0}color:gray{/if}">{if $record->news['count'] > 0}<a href="{url alias='film-news' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">{/if}Actualités{if $record->news['count'] > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">sur le film...</span></div>
	{if $menu == "cinema"}<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if count($record->story) == 0}color:gray{/if}">{if count($record->story) > 0}<a href="{url alias='bande-annonce-film' base=$record->base_type id=$record->get_id() title=$record->title_encode}" style="text-decoration:none;color:white;">{/if}Annecdotes{if count($record->story) > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">secrets de tournages...</span></div>{/if}
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;">
	<form name="like" method="post" action="{url alias='fiche-detail' base=$record->base_type id=$record->get_id() title=$record->title_encode}">
		<input type="hidden" name="like" value="1">
		<a href="javascript:void(0);" onCLick="document.like.submit();"><img src="/img/coeur.png"> <b style="font-size:18px;">{$like}</b>
	</form>
	</div>
</div>