{* version=2; *}
<div class="double_tier_left_bloc_black_menu">
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:6px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='acteur-detail' id=$actor->get_id() title=$actor->title_encode}"><img src="/img/home.png" width="32" alt="icone home" title="icone home" style="border:0px;"></a></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='acteur-biography' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">Biographie</a><br/><span style="color:gray;font-size:10px;">complète...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='acteur-filmography' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">Filmographie</a><br/><span style="color:gray;font-size:10px;">complète...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if $actor->photo['count'] == 0}color:gray{/if}">{if $actor->photo['count'] > 0}<a href="{url alias='acteur-photos' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">{/if}Photos{if $actor->photo['count'] > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">de l'acteur...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='acteur-recompenses' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">Récompenses</a><br/><span style="color:gray;font-size:10px;">complet...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if $actor->news['count'] == 0}color:gray{/if}">{if $actor->news['count'] > 0}<a href="{url alias='acteur-news' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">{/if}Actualités{if $actor->news['count'] > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">sur l'acteur...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;{if $actor->trailer['count'] == 0}color:gray{/if}">{if $actor->trailer['count'] > 0}<a href="{url alias='acteur-videos' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">{/if}Vidéos{if $actor->trailer['count'] > 0}</a>{/if}<br/><span style="color:gray;font-size:10px;">de l'acteur...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;"><a href="{url alias='acteur-dvd' id=$actor->get_id() title=$actor->title_encode}" style="text-decoration:none;color:white;">DVD</a><br/><span style="color:gray;font-size:10px;">Blu-ray...</span></div>
	<div class="right_and_left_bloc_black_menu_bloc" style="padding-top:12px;font-size:14px;padding-left:5px;padding-right:5px;text-align:center;">
	<form name="like" method="post" action="{url alias='acteur-detail' id=$actor->get_id() title=$actor->title_encode}">
		<input type="hidden" name="like" value="1">
		<a href="javascript:void(0);" onCLick="document.like.submit();"><img src="/img/coeur.png"> <b style="font-size:18px;">{$like}</b>
	</form>
	</div>
</div>